#!/bin/bash
# Builds STIX_V2.0_MASTER_PROTOCOL.md — COMPLETE rulebook (summaries + individual rules)
OUT="STIX_V2.0_MASTER_PROTOCOL.md"

cat > "$OUT" << 'HEADER'
# STIX — Structured Tiers for Integrated Execution
## V2.0 Master Protocol | 130 Rules | Complete Rulebook
**Version:** 2.0 | **Updated:** 2026-04-06
**Governing Values:** JUDGMENT | PRECISION | ALIGNMENT | INTEGRITY | TRANSPARENCY | SAFETY | EFFICIENCY

> Upload alongside CLAUDE.md to any AI system for full framework activation.
> This document contains complete rule definitions — not summaries.

---
HEADER

# BINDING SEQUENCE ORDER — summaries first, then detailed rules
SECTIONS=(
  # Base protocol (V1.1 source)
  "CORE_PROTOCOL/APEX_FORGE_CIPHER_MASTER_PROTOCOL_v4_2026-03-26_2046.md"
  # V2.0 protocols — summaries
  "VERDICT/VERDICT_SUMMARY.md"
  "ARCHITECT/ARCHITECT_SUMMARY.md"
  "APEX/EXECUTION/EXECUTION_SUMMARY.md"
  # Detailed APEX execution rules
  "APEX/EXECUTION/E13_CONFIDENCE_CRITERIA.md"
  "APEX/EXECUTION/E21_HUMAN_IN_LOOP_GATE.md"
  "APEX/EXECUTION/E22_MODULE_CAPABILITY_CONFLICT.md"
  "APEX/EXECUTION/E23_INPUT_SOURCE_VERIFICATION.md"
  "APEX/EXECUTION/E25_CONTEXT_COMPRESSION.md"
  "APEX/COMMUNICATION/COMMUNICATION_SUMMARY.md"
  "APEX/COMMUNICATION/C14_LANGUAGE_PRECISION.md"
  "APEX/COMMUNICATION/C15_INTERRUPT_RECOVERY.md"
  "APEX/EXACTNESS/EXACTNESS_SUMMARY.md"
  "APEX/EXACTNESS/X13_POINTER_RESOLUTION.md"
  "FORGE/FORGE_SUMMARY.md"
  "FORGE/F13_ACTIVE_COMPLIANCE_VERIFICATION.md"
  "CIPHER/CIPHER_SUMMARY.md"
  "CIPHER/G8_CIPHER_UNIVERSAL_TRIGGER.md"
  "CIPHER/G9_FINANCIAL_DECISION_GATE.md"
  "CIPHER/G10_CODE_TO_PRODUCTION_GATE.md"
  "CIPHER/G11_PUBLISHED_ARTIFACT_GATE.md"
  "RELAY/RELAY_SUMMARY.md"
  "OBSERVE/OBSERVE_SUMMARY.md"
  "OBSERVE/OB1_EVERY_OUTPUT_AUDITABLE.md"
  "OBSERVE/OB2_COMPLIANCE_CHECK_AT_OUTPUT.md"
  "OBSERVE/OB3_DRIFT_DETECTION.md"
  "OBSERVE/OB4_SESSION_ENTROPY_METER.md"
  "OBSERVE/OB5_CONFIDENCE_JUSTIFICATION.md"
  "OBSERVE/OB6_VIOLATION_LOGGING.md"
  "OBSERVE/OB7_METRICS_COLLECTION.md"
  "OBSERVE/OB8_FRAMEWORK_DRIFT_TRACKING.md"
  "RISK/RISK_SUMMARY.md"
  "ECON/ECON_SUMMARY.md"
  "GOVERNING_BOUNDARIES/GOVERNING_BOUNDARIES_SUMMARY.md"
  "GOVERNING_BOUNDARIES/B4_NO_UNILATERAL_CONTENT.md"
  "GOVERNING_BOUNDARIES/B5_NO_SILENT_CONTINUITY.md"
  "GOVERNING_BOUNDARIES/B6_NO_FINAL_WITHOUT_CONFIRMATION.md"
  "GOVERNING_BOUNDARIES/B7_NO_SCOPE_EXPANSION.md"
  # Appendices
  "CORE_PROTOCOL/APPENDIX_C_ERROR_CLASSIFICATION.md"
  "CORE_PROTOCOL/APPENDIX_D_OPERATING_CADENCE.md"
)

for f in "${SECTIONS[@]}"; do
  if [ -f "$f" ]; then
    echo -e "\n---\n" >> "$OUT"
    cat "$f" >> "$OUT"
  fi
done
echo "✅ Complete rulebook built: $OUT ($(wc -l < "$OUT") lines)"
